baseURL = "https://mentat.za.net/blog/"
languageCode = "en-us"
title = "Stéfan's blog"
theme = ["hugo-atom-feed", "tale-hugo"]
disqusShortname = "stefanvdwalt"

pygmentsCodeFences = true
pygmentsStyle = "friendly"

[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename"]

[params]
author = "Stéfan van der Walt"
css = ["custom.css"]

[permalinks]
  # mimic pelican permalink configuration
  posts = "/:year/:month/:day/:slug/"

[mediaTypes]
[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "atom"
isPlainText = false

[outputs]
home = ["HTML", "ATOM"]
