baseURL = "http://mentat.za.net/blog/"
languageCode = "en-us"
title = "Stéfan's blog"
theme = "tale-hugo"
disqusShortname = "stefanvdwalt"

[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename"]

[params]
author = "Stéfan van der Walt"

[permalinks]
  # mimic pelican permalink configuration
  posts = "/:year/:month/:day/:slug/"

[mediaTypes]
[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "atom"
isPlainText = false

[outputs]
home = ["HTML", "Atom"]
