baseURL = "https://mentat.za.net/blog/"
languageCode = "en-us"
title = "Stéfan's blog"
theme = ["hugo-atom-feed", "tale-hugo"]
disqusShortname = "stefanvdwalt"
disableKinds = ["RSS"]

#pygmentsCodeFences = true
#pygmentsStyle = "friendly"

[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename"]

[params]
css = ["custom.css", "witchhazel.css"]
feedSections = ["posts", "personal"]
comments = true
author = { name = "Stéfan van der Walt" }

[permalinks]
  # mimic pelican permalink configuration
  posts = "/:year/:month/:day/:slug/"
  personal = "/:year/:month/:day/:slug/"

[mediaTypes]
[mediaTypes."application/atom"]
suffixes = ["xml"]

[outputFormats.Atom]
mediaType = "application/atom"
baseName = "atom"
isPlainText = false

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML", "ATOM"]
term = ["HTML", "ATOM"]

[markup.highlight]
style = "witchhazel"
noClasses = false

[goldmark.renderHooks.image]
enableDefault = true

[goldmark.renderHooks.link]
enableDefault = true
